-- Migration: 03_seed_dev_client.sql
-- OPCIONAL: solo para entornos de desarrollo. Crea un api_client de prueba.
-- NO ejecutar en produccion.
--
-- El api_key tiene formato: "<prefix>.<secret>"
-- Para generar uno completo en local desde Node:
--
--   node -e "
--   const c = require('crypto');
--   const a = require('argon2');
--   const prefix = 'eai_' + c.randomBytes(6).toString('hex');
--   const secret = c.randomBytes(24).toString('base64url');
--   a.hash(secret).then(h => console.log({apiKey: prefix + '.' + secret, prefix, hash: h}));
--   "
--
-- Luego usa el "apiKey" devuelto en el header X-Api-Key del frontend EMR
-- y registra (prefix, hash) en la tabla.

-- insert into public.api_clients (name, api_key_prefix, api_key_hash, jwks_url, is_active)
-- values (
--   'local-dev',
--   'eai_xxxxxxxx',
--   '$argon2id$v=19$m=65536,t=3,p=4$AAAA...',
--   'https://your-emr-project.supabase.co/auth/v1/.well-known/jwks.json',
--   true
-- );
